version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pr-reviewer-service-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pr_service_password
      POSTGRES_DB: pr_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
